-- Generated by Cloud Spanner Graph DDL Architect
--
-- Non-Translatable OWL Capabilities (System Gaps):
-- The following OWL constructs are not directly translatable into the Spanner schema
-- and must be enforced by the application logic.
--
-- 1. Cardinality Constraints:
--    - owl:maxCardinality "3" on PersonalAccount.hasSignatory.
--    - owl:cardinality "1" on CorporateAccount.hasOwner.
--
-- 2. Polymorphic Transitive Property:
--    - owl:TransitiveProperty 'subAccountOf' has a domain and range of the abstract 'Account' class.
--      Given the 'Table-Per-Class' physical design with separate tables for 'PersonalAccounts'
--      and 'CorporateAccounts', a single edge definition in the property graph cannot reference
--      multiple destination node tables. The 'AccountHierarchy' table is created for SQL-based
--      traversal, but this relationship is omitted from the GQL graph schema.
--
-- 3. Other Property Characteristics:
--    - owl:propertyDisjointWith, owl:propertyChainAxiom, owl:IrreflexiveProperty, owl:AsymmetricProperty
--      are not supported by the DDL and require application-level validation.

-- =============================================================================
-- 1. Physical Relational DDL (Table-Per-Class)
-- =============================================================================

-- FAIL_VALIDATION

-- Node Tables for Party Hierarchy
CREATE TABLE Persons (
    PersonId STRING(36) NOT NULL,
    -- Other person-specific attributes would be defined here.
) PRIMARY KEY (PersonId);

CREATE TABLE Organizations (
    OrganizationId STRING(36) NOT NULL,
    -- Other organization-specific attributes would be defined here.
) PRIMARY KEY (OrganizationId);

-- Node Tables for Account Hierarchy
CREATE TABLE PersonalAccounts (
    PersonalAccountId STRING(36) NOT NULL,
    AccountBalance NUMERIC NOT NULL,
    OwnerPersonId STRING(36) NOT NULL,
    IsHighRisk BOOL NOT NULL AS (AccountBalance > 100000.0) STORED,
    CONSTRAINT FK_PersonalAccount_Owner FOREIGN KEY (OwnerPersonId) REFERENCES Persons (PersonId),
) PRIMARY KEY (PersonalAccountId);

CREATE TABLE CorporateAccounts (
    CorporateAccountId STRING(36) NOT NULL,
    AccountBalance NUMERIC NOT NULL,
    OwnerOrganizationId STRING(36) NOT NULL,
    IsHighRisk BOOL NOT NULL AS (AccountBalance > 100000.0) STORED,
    CONSTRAINT FK_CorporateAccount_Owner FOREIGN KEY (OwnerOrganizationId) REFERENCES Organizations (OrganizationId),
) PRIMARY KEY (CorporateAccountId);

-- Edge Table for 'hasSignatory' relationship (PersonalAccount -> Person)
CREATE TABLE PersonalAccountSignatories (
    PersonalAccountId STRING(36) NOT NULL,
    SignatoryPersonId STRING(36) NOT NULL,
    CONSTRAINT FK_Signatory_Account FOREIGN KEY (PersonalAccountId) REFERENCES PersonalAccounts (PersonalAccountId) ON DELETE CASCADE,
    CONSTRAINT FK_Signatory_Person FOREIGN KEY (SignatoryPersonId) REFERENCES Persons (PersonId) ON DELETE CASCADE,
) PRIMARY KEY (PersonalAccountId, SignatoryPersonId);

-- Edge Table for 'isPartnerOf' symmetric relationship (Organization <-> Organization)
CREATE TABLE OrganizationPartnerships (
    OrganizationId1 STRING(36) NOT NULL,
    OrganizationId2 STRING(36) NOT NULL,
    CONSTRAINT FK_Partner_Org1 FOREIGN KEY (OrganizationId1) REFERENCES Organizations (OrganizationId) ON DELETE CASCADE,
    CONSTRAINT FK_Partner_Org2 FOREIGN KEY (OrganizationId2) REFERENCES Organizations (OrganizationId) ON DELETE CASCADE,
    -- Enforce canonical order to store each symmetric pair only once
    CONSTRAINT Chk_OrgPartner_Order CHECK (OrganizationId1 < OrganizationId2),
) PRIMARY KEY (OrganizationId1, OrganizationId2);

-- Edge Table for 'subAccountOf' transitive relationship (Account -> Account)
-- NOTE: This table supports SQL-based path queries but is not included in the
-- property graph DDL due to polymorphic foreign key limitations.
CREATE TABLE AccountHierarchy (
    ParentAccountId STRING(36) NOT NULL,
    ChildAccountId STRING(36) NOT NULL,
) PRIMARY KEY (ParentAccountId, ChildAccountId);


-- =============================================================================
-- 2. Logical Labeled Property Graph DDL
-- =============================================================================

CREATE PROPERTY GRAPH FintechGraph
    -- Node table definitions with multi-label inheritance
    NODE TABLE Persons
        KEY (PersonId)
        LABEL Person PROPERTIES (PersonId),
        LABEL Party PROPERTIES (PersonId AS PartyId)

    NODE TABLE Organizations
        KEY (OrganizationId)
        LABEL Organization PROPERTIES (OrganizationId),
        LABEL Party PROPERTIES (OrganizationId AS PartyId)

    NODE TABLE PersonalAccounts
        KEY (PersonalAccountId)
        LABEL PersonalAccount PROPERTIES (PersonalAccountId, AccountBalance, IsHighRisk),
        LABEL Account PROPERTIES (PersonalAccountId AS AccountId, AccountBalance, IsHighRisk)

    NODE TABLE CorporateAccounts
        KEY (CorporateAccountId)
        LABEL CorporateAccount PROPERTIES (CorporateAccountId, AccountBalance, IsHighRisk),
        LABEL Account PROPERTIES (CorporateAccountId AS AccountId, AccountBalance, IsHighRisk)

    -- Edge definitions
    -- 'hasOwner' is modeled as a property on account tables.
    -- The inverse 'ownsAccount' is handled by GQL query direction.
    EDGE TABLE PersonalAccounts
        SOURCE KEY (PersonalAccountId) REFERENCES PersonalAccounts
        DESTINATION KEY (OwnerPersonId) REFERENCES Persons
        LABEL hasOwner PROPERTIES (PersonalAccountId AS AccountId, OwnerPersonId AS OwnerId)

    EDGE TABLE CorporateAccounts
        SOURCE KEY (CorporateAccountId) REFERENCES CorporateAccounts
        DESTINATION KEY (OwnerOrganizationId) REFERENCES Organizations
        LABEL hasOwner PROPERTIES (CorporateAccountId AS AccountId, OwnerOrganizationId AS OwnerId)

    -- 'hasSignatory' is modeled in a dedicated join table.
    EDGE TABLE PersonalAccountSignatories
        SOURCE KEY (PersonalAccountId) REFERENCES PersonalAccounts
        DESTINATION KEY (SignatoryPersonId) REFERENCES Persons
        LABEL hasSignatory PROPERTIES (PersonalAccountId, SignatoryPersonId)

    -- 'isPartnerOf' is a symmetric property. NO_INVERSE allows bidirectional traversal.
    EDGE TABLE OrganizationPartnerships
        SOURCE KEY (OrganizationId1) REFERENCES Organizations
        DESTINATION KEY (OrganizationId2) REFERENCES Organizations
        NO_INVERSE
        LABEL isPartnerOf PROPERTIES (OrganizationId1, OrganizationId2)
;