-- Generated by a Cloud Spanner Graph DDL Architect
--
-- Source OWL Ontology: Fintech Compliance Ontology (http://example.org/fintech/)
--
-- ----------------------------------------------------------------------------
-- Non-Translatable OWL Capabilities (System Gaps)
-- ----------------------------------------------------------------------------
-- The following OWL constructs are not directly translatable into Spanner DDL
-- and must be enforced in the application layer:
--
-- 1. Cardinality Constraints:
--    - owl:maxCardinality="3" on PersonalAccount.hasSignatory.
--    - owl:cardinality="1" on CorporateAccount.hasOwner (partially enforced with NOT NULL).
--
-- 2. Transitive Property with Table-Per-Class:
--    - The owl:TransitiveProperty 'subAccountOf' is defined on the abstract 'Account' class.
--    - The strict Table-Per-Class pattern creates separate tables for 'PersonalAccount' and 'CorporateAccount'.
--    - This prevents the use of a single Spanner INTERLEAVE IN PARENT table for the hierarchy, as no single parent table exists.
--    - The relationship is instead modeled with a non-interleaved 'AccountHierarchy' join table. Referential integrity for this
--      table must be managed by the application, as DDL foreign keys cannot target multiple tables.
--
-- 3. Other Property Characteristics:
--    - owl:propertyDisjointWith, owl:IrreflexiveProperty, owl:AsymmetricProperty, owl:propertyChainAxiom.
-- ----------------------------------------------------------------------------


-- ============================================================================
-- Part 1: Physical Relational DDL (Table-Per-Class)
-- ============================================================================

-- Node Tables for Party Hierarchy
-- Disjointness between Person and Organization is enforced by separate tables.

CREATE TABLE Persons (
    PersonId STRING(36) NOT NULL,
    FullName STRING(255),
    DateOfBirth DATE,
) PRIMARY KEY (PersonId);

CREATE TABLE Organizations (
    OrganizationId STRING(36) NOT NULL,
    LegalName STRING(255),
    TaxId STRING(100),
) PRIMARY KEY (OrganizationId);


-- Node Tables for Account Hierarchy
-- Disjointness between PersonalAccount and CorporateAccount is enforced by separate tables.
-- Superclass (Account) properties are flattened into these concrete tables.

CREATE TABLE PersonalAccounts (
    AccountId STRING(36) NOT NULL,
    -- Flattened from ex:Account
    AccountBalance NUMERIC NOT NULL,
    -- From ex:hasOwner restriction with owl:allValuesFrom ex:Person
    OwnerPersonId STRING(36) NOT NULL,
    -- From ex:HighRiskAccount equivalentClass rule
    IsHighRisk BOOL NOT NULL AS (AccountBalance > 100000.0) STORED,
    CONSTRAINT FK_PersonalAccount_Owner FOREIGN KEY (OwnerPersonId) REFERENCES Persons (PersonId)
) PRIMARY KEY (AccountId);

CREATE TABLE CorporateAccounts (
    AccountId STRING(36) NOT NULL,
    -- Flattened from ex:Account
    AccountBalance NUMERIC NOT NULL,
    -- From ex:hasOwner restriction with owl:allValuesFrom ex:Organization and owl:cardinality "1"
    OwnerOrganizationId STRING(36) NOT NULL,
    -- From ex:HighRiskAccount equivalentClass rule
    IsHighRisk BOOL NOT NULL AS (AccountBalance > 100000.0) STORED,
    CONSTRAINT FK_CorporateAccount_Owner FOREIGN KEY (OwnerOrganizationId) REFERENCES Organizations (OrganizationId)
) PRIMARY KEY (AccountId);


-- Edge (Join) Tables for Relationships

-- Models the many-to-many 'hasSignatory' relationship
CREATE TABLE PersonalAccountSignatories (
    AccountId STRING(36) NOT NULL,
    PersonId STRING(36) NOT NULL,
    CONSTRAINT FK_Signatory_Account FOREIGN KEY (AccountId) REFERENCES PersonalAccounts (AccountId),
    CONSTRAINT FK_Signatory_Person FOREIGN KEY (PersonId) REFERENCES Persons (PersonId)
) PRIMARY KEY (AccountId, PersonId);

-- Models the symmetric 'isPartnerOf' relationship
CREATE TABLE OrganizationPartners (
    OrganizationId1 STRING(36) NOT NULL,
    OrganizationId2 STRING(36) NOT NULL,
    CONSTRAINT FK_Partner_Org1 FOREIGN KEY (OrganizationId1) REFERENCES Organizations (OrganizationId),
    CONSTRAINT FK_Partner_Org2 FOREIGN KEY (OrganizationId2) REFERENCES Organizations (OrganizationId),
    -- Enforces storing the symmetric relationship in a single, canonical direction
    CONSTRAINT CHK_Partner_Symmetry CHECK (OrganizationId1 < OrganizationId2)
) PRIMARY KEY (OrganizationId1, OrganizationId2);

-- Models the transitive 'subAccountOf' relationship
CREATE TABLE AccountHierarchy (
    ParentAccountId STRING(36) NOT NULL,
    ChildAccountId STRING(36) NOT NULL,
) PRIMARY KEY (ParentAccountId, ChildAccountId);


-- ============================================================================
-- Part 2: Logical Labeled Property Graph DDL
-- ============================================================================

CREATE PROPERTY GRAPH FintechGraph
    --
    -- Node Table Definitions
    -- Multi-label inheritance (e.g., Person -> Party) is modeled with multiple LABEL clauses.
    --
    NODE TABLE Persons
        PRIMARY KEY (PersonId)
        LABEL Person PROPERTIES (ALL COLUMNS)
        LABEL Party PROPERTIES () -- Party has no unique properties in the ontology
    NODE TABLE Organizations
        PRIMARY KEY (OrganizationId)
        LABEL Organization PROPERTIES (ALL COLUMNS)
        LABEL Party PROPERTIES () -- Party has no unique properties in the ontology
    NODE TABLE PersonalAccounts
        PRIMARY KEY (AccountId)
        LABEL PersonalAccount PROPERTIES (ALL COLUMNS)
        LABEL Account PROPERTIES (AccountId, AccountBalance, IsHighRisk)
    NODE TABLE CorporateAccounts
        PRIMARY KEY (AccountId)
        LABEL CorporateAccount PROPERTIES (ALL COLUMNS)
        LABEL Account PROPERTIES (AccountId, AccountBalance, IsHighRisk)

    --
    -- Edge Table Definitions
    --
    EDGE TABLE PersonalAccountSignatories
        SOURCE KEY (AccountId) REFERENCES PersonalAccounts (AccountId)
        DESTINATION KEY (PersonId) REFERENCES Persons (PersonId)
        LABEL hasSignatory PROPERTIES ()

    EDGE TABLE OrganizationPartners
        SOURCE KEY (OrganizationId1) REFERENCES Organizations (OrganizationId)
        DESTINATION KEY (OrganizationId2) REFERENCES Organizations (OrganizationId)
        -- The 'isPartnerOf' property is symmetric; GQL queries can traverse this edge
        -- bidirectionally, e.g., MATCH (o1)-[:isPartnerOf]-(o2)
        LABEL isPartnerOf PROPERTIES ()

    -- The 'hasOwner' relationship is embedded as a foreign key in the account tables.
    -- We define edges on these tables, aliasing columns to conform to the Shared Label Uniformity rule.
    -- The inverse property 'ownsAccount' is not stored physically but is queryable via GQL direction reversal.
    EDGE TABLE PersonalAccounts AS PersonalAccountOwners
        SOURCE KEY (AccountId) REFERENCES PersonalAccounts (AccountId)
        DESTINATION KEY (OwnerPersonId) REFERENCES Persons (PersonId)
        LABEL hasOwner PROPERTIES (OwnerPersonId AS OwnerId)

    EDGE TABLE CorporateAccounts AS CorporateAccountOwners
        SOURCE KEY (AccountId) REFERENCES CorporateAccounts (AccountId)
        DESTINATION KEY (OwnerOrganizationId) REFERENCES Organizations (OrganizationId)
        LABEL hasOwner PROPERTIES (OwnerOrganizationId AS OwnerId)

    -- The 'subAccountOf' relationship connects different types of accounts. We must define an
    -- edge for each possible combination, all sharing the same physical table and label.
    -- The transitive nature is handled in GQL queries via variable-length path matching, e.g., -[:subAccountOf*]->
    EDGE TABLE AccountHierarchy AS SubAccount_PP
        SOURCE KEY (ParentAccountId) REFERENCES PersonalAccounts (AccountId)
        DESTINATION KEY (ChildAccountId) REFERENCES PersonalAccounts (AccountId)
        LABEL subAccountOf PROPERTIES ()
    EDGE TABLE AccountHierarchy AS SubAccount_PC
        SOURCE KEY (ParentAccountId) REFERENCES PersonalAccounts (AccountId)
        DESTINATION KEY (ChildAccountId) REFERENCES CorporateAccounts (AccountId)
        LABEL subAccountOf PROPERTIES ()
    EDGE TABLE AccountHierarchy AS SubAccount_CP
        SOURCE KEY (ParentAccountId) REFERENCES CorporateAccounts (AccountId)
        DESTINATION KEY (ChildAccountId) REFERENCES PersonalAccounts (AccountId)
        LABEL subAccountOf PROPERTIES ()
    EDGE TABLE AccountHierarchy AS SubAccount_CC
        SOURCE KEY (ParentAccountId) REFERENCES CorporateAccounts (AccountId)
        DESTINATION KEY (ChildAccountId) REFERENCES CorporateAccounts (AccountId)
        LABEL subAccountOf PROPERTIES ()
;